services:
  # MySQL Database (auto-imports SQL files)
  mysql:
    image: mysql:5.7
    container_name: wp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - wp_network

  # Custom Nginx Reverse Proxy
  nginx:
    build: ./nginx
    container_name: wp_nginx
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - wp_network

  # High-Traffic Sites (10 isolated containers)
  casino-en-ligne:
    image: wordpress:php8.3-fpm
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
    volumes:
      - ./moneysites/casino-en-ligne:/var/www/html/
    networks:
      - wp_network

  jeux-ca:
    image: wordpress:php8.3-fpm
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
    volumes:
      - ./moneysites/jeux-ca:/var/www/html/
    networks:
      - wp_network

  # ... Repeat for site2 to site10

  # Low-Traffic Sites (100 sites in 1 shared container)
  minisites:
    image: wordpress:php8.3-fpm
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
    volumes:
      - ./minisites:/var/www/html/
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
